name: ci-fullstack-workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend  # Adjust this path to where your package.json is located

      - name: Run tests
        run: npm test
        working-directory: ./frontend

      - name: Run linter
        run: npm run lint
        working-directory: ./frontend

      - name: Completion message
        run: |
          echo "Hello ${{ github.actor }}. You pushed to ${{ github.repository }} at $(date)."
