name: ci-fullstack-workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: cd backend && npm install  # No working-directory if package.json is in root

      - name: Run tests
        run: cd backend && npm test  # No working-directory if package.json is in root

      - name: Run linter
        run: cd backend/node_modules && npm init @eslint/config && npm run lint  # No working-directory if package.json is in root

      - name: Completion message
        run: |
          echo "Hello ${{ github.actor }}. You pushed to ${{ github.repository }} at $(date)."
